const PARSE_RESULT = {
    EXPECT_VALUE: "EXPECT_VALUE",
    INVALID_VALUE: "INVALID_VALUE",
    ROOT_NOT_SINGULAR: "ROOT_NOT_SINGULAR",
    NUMBER_TOO_BIG: "NUMBER_TOO_BIG",
    MISS_QUOTATION_MARK: "MISS_QUOTATION_MARK",
    INVALID_STRING_ESCAPE: "INVALID_STRING_ESCAPE",
    INVALID_STRING_CHAR: "INVALID_STRING_CHAR",
    INVALID_UNICODE_HEX: "INVALID_UNICODE_HEX",
    INVALID_UNICODE_SURROGATE: "INVALID_UNICODE_SURROGATE",
    MISS_COMMA_OR_SQUARE_BRACKET: "MISS_COMMA_OR_SQUARE_BRACKET",
    MISS_KEY: "MISS_KEY",
    MISS_COLON: "MISS_COLON",
    MISS_COMMA_OR_CURLY_BRACKET: "MISS_COMMA_OR_CURLY_BRACKET",
}
module.exports.PARSE_RESULT = PARSE_RESULT